source ~/env.z.sh
source ~/.files/zsh/config.z.sh
source ~/.files/zsh/colors.z.sh
source ~/.files/zsh/plugins.z.sh
source ~/.files/zsh/dir.z.sh
source ~/.files/zsh/alias/ubuntu.z.sh
source ~/.files/zsh/docker.z.sh
source ~/.files/zsh/projects.z.sh
source ~/.files/zsh/source.z.sh
source ~/.files/zsh/git.z.sh
source ~/.files/zsh/personal.z.sh
source ~/.files/zsh/session.z.sh
source ~/.files/zsh/hotfix.z.sh
source ~/.files/zsh/todo.z.sh
