PASSWORD="XXXX"
STORAGE="XXXX"

# Windows User Directory
WINDOWS_USER_DIRECTORY="XXXX"

# Configuration Directories
GLAZE_DIRECTORY="XXXX"
VS_DIRECTORY="XXXX"
OBS_DIRECTORY="XXXX"

# Bos Eriko Main Projects Directories
BOS_ERIKO_PLUS_DIRECTORY="XXXX"
BOS_ERIKO_COM_DIRECTORY="XXXX"
BOTERIKO_DIRECTORY="XXXX"
OVERLAY_DIRECTORY="XXXX"

# Tokens
TODOIST_TOKEN="XXXX"