PASSWORD="XXXX"
STORAGE="XXXX"

# Windows User Directory
WINDOWS_USER_DIRECTORY="XXXX"

# Configuration Directories
GLAZE_DIRECTORY="XXXX"
VS_DIRECTORY="XXXX"
OBS_DIRECTORY="XXXX"
CHATTY_DIRECTORY="XXXX"

# Bos Eriko Directories
BOS_ERIKO_DATA_DIRECTORY="XXXX"

# Purrintables Directory
PURRINTABLES_DIRECTORY="XXXX"

# ReferScout Directory
REFERSCOUT_DIRECTORY="XXXX"

# AdminNow Directory
ADMIN_NOW_SERVER_DIRECTORY="XXXX"
ADMIN_NOW_WEBSITE_DIRECTORY="XXXX"